apiVersion: apps/v1
kind: Deployment
metadata:
  name: netconf-router-deployment
  labels:
    app: netconf-router
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netconf-router
  template:
    metadata:
      labels:
        app: netconf-router
    spec:
      containers:
      - name: netconf-router
        image: sysrepo/sysrepo-netopeer2:latest
        ports:
        - containerPort: 830
          name: netconf
          protocol: TCP
        env:
        - name: EDITOR
          value: "vim"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 830
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 830
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: netconf-router-service
  labels:
    app: netconf-router
spec:
  type: ClusterIP
  selector:
    app: netconf-router
  ports:
  - port: 830
    targetPort: 830
    protocol: TCP
    name: netconf
